// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package graphql

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// DeleteMediaListEntryDeleteMediaListEntryDeleted includes the requested fields of the GraphQL type Deleted.
// The GraphQL type's documentation follows.
//
// Deleted data type
type DeleteMediaListEntryDeleteMediaListEntryDeleted struct {
	// If an item has been successfully deleted
	Deleted bool `json:"deleted"`
}

// GetDeleted returns DeleteMediaListEntryDeleteMediaListEntryDeleted.Deleted, and is useful for accessing the field via an interface.
func (v *DeleteMediaListEntryDeleteMediaListEntryDeleted) GetDeleted() bool { return v.Deleted }

// DeleteMediaListEntryResponse is returned by DeleteMediaListEntry on success.
type DeleteMediaListEntryResponse struct {
	// Delete a media list entry
	DeleteMediaListEntry DeleteMediaListEntryDeleteMediaListEntryDeleted `json:"DeleteMediaListEntry"`
}

// GetDeleteMediaListEntry returns DeleteMediaListEntryResponse.DeleteMediaListEntry, and is useful for accessing the field via an interface.
func (v *DeleteMediaListEntryResponse) GetDeleteMediaListEntry() DeleteMediaListEntryDeleteMediaListEntryDeleted {
	return v.DeleteMediaListEntry
}

// GetAnimeDetailsMedia includes the requested fields of the GraphQL type Media.
// The GraphQL type's documentation follows.
//
// Anime or Manga
type GetAnimeDetailsMedia struct {
	// The id of the media
	Id int `json:"id"`
	// The mal id of the media
	IdMal int `json:"idMal"`
	// The official titles of the media in various languages
	Title GetAnimeDetailsMediaTitle `json:"title"`
	// The type of the media; anime or manga
	Type MediaType `json:"type"`
	// The banner image of the media
	BannerImage string `json:"bannerImage"`
	// The cover images of the media
	CoverImage GetAnimeDetailsMediaCoverImage `json:"coverImage"`
	// Short description of the media's story and characters
	Description string `json:"description"`
	// The format the media was released in
	Format MediaFormat `json:"format"`
	// The amount of episodes the anime has when complete
	Episodes int `json:"episodes"`
	// The first official release date of the media
	StartDate GetAnimeDetailsMediaStartDateFuzzyDate `json:"startDate"`
}

// GetId returns GetAnimeDetailsMedia.Id, and is useful for accessing the field via an interface.
func (v *GetAnimeDetailsMedia) GetId() int { return v.Id }

// GetIdMal returns GetAnimeDetailsMedia.IdMal, and is useful for accessing the field via an interface.
func (v *GetAnimeDetailsMedia) GetIdMal() int { return v.IdMal }

// GetTitle returns GetAnimeDetailsMedia.Title, and is useful for accessing the field via an interface.
func (v *GetAnimeDetailsMedia) GetTitle() GetAnimeDetailsMediaTitle { return v.Title }

// GetType returns GetAnimeDetailsMedia.Type, and is useful for accessing the field via an interface.
func (v *GetAnimeDetailsMedia) GetType() MediaType { return v.Type }

// GetBannerImage returns GetAnimeDetailsMedia.BannerImage, and is useful for accessing the field via an interface.
func (v *GetAnimeDetailsMedia) GetBannerImage() string { return v.BannerImage }

// GetCoverImage returns GetAnimeDetailsMedia.CoverImage, and is useful for accessing the field via an interface.
func (v *GetAnimeDetailsMedia) GetCoverImage() GetAnimeDetailsMediaCoverImage { return v.CoverImage }

// GetDescription returns GetAnimeDetailsMedia.Description, and is useful for accessing the field via an interface.
func (v *GetAnimeDetailsMedia) GetDescription() string { return v.Description }

// GetFormat returns GetAnimeDetailsMedia.Format, and is useful for accessing the field via an interface.
func (v *GetAnimeDetailsMedia) GetFormat() MediaFormat { return v.Format }

// GetEpisodes returns GetAnimeDetailsMedia.Episodes, and is useful for accessing the field via an interface.
func (v *GetAnimeDetailsMedia) GetEpisodes() int { return v.Episodes }

// GetStartDate returns GetAnimeDetailsMedia.StartDate, and is useful for accessing the field via an interface.
func (v *GetAnimeDetailsMedia) GetStartDate() GetAnimeDetailsMediaStartDateFuzzyDate {
	return v.StartDate
}

// GetAnimeDetailsMediaCoverImage includes the requested fields of the GraphQL type MediaCoverImage.
type GetAnimeDetailsMediaCoverImage struct {
	// The cover image url of the media at a large size
	Large string `json:"large"`
	// The cover image url of the media at its largest size. If this size isn't available, large will be provided instead.
	ExtraLarge string `json:"extraLarge"`
}

// GetLarge returns GetAnimeDetailsMediaCoverImage.Large, and is useful for accessing the field via an interface.
func (v *GetAnimeDetailsMediaCoverImage) GetLarge() string { return v.Large }

// GetExtraLarge returns GetAnimeDetailsMediaCoverImage.ExtraLarge, and is useful for accessing the field via an interface.
func (v *GetAnimeDetailsMediaCoverImage) GetExtraLarge() string { return v.ExtraLarge }

// GetAnimeDetailsMediaStartDateFuzzyDate includes the requested fields of the GraphQL type FuzzyDate.
// The GraphQL type's documentation follows.
//
// Date object that allows for incomplete date values (fuzzy)
type GetAnimeDetailsMediaStartDateFuzzyDate struct {
	// Numeric Year (2017)
	Year int `json:"year"`
	// Numeric Month (3)
	Month int `json:"month"`
	// Numeric Day (24)
	Day int `json:"day"`
}

// GetYear returns GetAnimeDetailsMediaStartDateFuzzyDate.Year, and is useful for accessing the field via an interface.
func (v *GetAnimeDetailsMediaStartDateFuzzyDate) GetYear() int { return v.Year }

// GetMonth returns GetAnimeDetailsMediaStartDateFuzzyDate.Month, and is useful for accessing the field via an interface.
func (v *GetAnimeDetailsMediaStartDateFuzzyDate) GetMonth() int { return v.Month }

// GetDay returns GetAnimeDetailsMediaStartDateFuzzyDate.Day, and is useful for accessing the field via an interface.
func (v *GetAnimeDetailsMediaStartDateFuzzyDate) GetDay() int { return v.Day }

// GetAnimeDetailsMediaTitle includes the requested fields of the GraphQL type MediaTitle.
// The GraphQL type's documentation follows.
//
// The official titles of the media in various languages
type GetAnimeDetailsMediaTitle struct {
	// The romanization of the native language title
	Romaji string `json:"romaji"`
}

// GetRomaji returns GetAnimeDetailsMediaTitle.Romaji, and is useful for accessing the field via an interface.
func (v *GetAnimeDetailsMediaTitle) GetRomaji() string { return v.Romaji }

// GetAnimeDetailsResponse is returned by GetAnimeDetails on success.
type GetAnimeDetailsResponse struct {
	// Media query
	Media GetAnimeDetailsMedia `json:"Media"`
}

// GetMedia returns GetAnimeDetailsResponse.Media, and is useful for accessing the field via an interface.
func (v *GetAnimeDetailsResponse) GetMedia() GetAnimeDetailsMedia { return v.Media }

// GetAnimeIdMedia includes the requested fields of the GraphQL type Media.
// The GraphQL type's documentation follows.
//
// Anime or Manga
type GetAnimeIdMedia struct {
	// The id of the media
	Id int `json:"id"`
}

// GetId returns GetAnimeIdMedia.Id, and is useful for accessing the field via an interface.
func (v *GetAnimeIdMedia) GetId() int { return v.Id }

// GetAnimeIdResponse is returned by GetAnimeId on success.
type GetAnimeIdResponse struct {
	// Media query
	Media GetAnimeIdMedia `json:"Media"`
}

// GetMedia returns GetAnimeIdResponse.Media, and is useful for accessing the field via an interface.
func (v *GetAnimeIdResponse) GetMedia() GetAnimeIdMedia { return v.Media }

// GetPopularAnimePage includes the requested fields of the GraphQL type Page.
// The GraphQL type's documentation follows.
//
// Page of data
type GetPopularAnimePage struct {
	Media []GetPopularAnimePageMedia `json:"media"`
}

// GetMedia returns GetPopularAnimePage.Media, and is useful for accessing the field via an interface.
func (v *GetPopularAnimePage) GetMedia() []GetPopularAnimePageMedia { return v.Media }

// GetPopularAnimePageMedia includes the requested fields of the GraphQL type Media.
// The GraphQL type's documentation follows.
//
// Anime or Manga
type GetPopularAnimePageMedia struct {
	// The id of the media
	Id int `json:"id"`
	// The mal id of the media
	IdMal int `json:"idMal"`
	// The official titles of the media in various languages
	Title GetPopularAnimePageMediaTitle `json:"title"`
	// The type of the media; anime or manga
	Type MediaType `json:"type"`
	// The banner image of the media
	BannerImage string `json:"bannerImage"`
	// The cover images of the media
	CoverImage GetPopularAnimePageMediaCoverImage `json:"coverImage"`
	// Short description of the media's story and characters
	Description string `json:"description"`
	// The format the media was released in
	Format MediaFormat `json:"format"`
	// The amount of episodes the anime has when complete
	Episodes int `json:"episodes"`
	// The first official release date of the media
	StartDate GetPopularAnimePageMediaStartDateFuzzyDate `json:"startDate"`
}

// GetId returns GetPopularAnimePageMedia.Id, and is useful for accessing the field via an interface.
func (v *GetPopularAnimePageMedia) GetId() int { return v.Id }

// GetIdMal returns GetPopularAnimePageMedia.IdMal, and is useful for accessing the field via an interface.
func (v *GetPopularAnimePageMedia) GetIdMal() int { return v.IdMal }

// GetTitle returns GetPopularAnimePageMedia.Title, and is useful for accessing the field via an interface.
func (v *GetPopularAnimePageMedia) GetTitle() GetPopularAnimePageMediaTitle { return v.Title }

// GetType returns GetPopularAnimePageMedia.Type, and is useful for accessing the field via an interface.
func (v *GetPopularAnimePageMedia) GetType() MediaType { return v.Type }

// GetBannerImage returns GetPopularAnimePageMedia.BannerImage, and is useful for accessing the field via an interface.
func (v *GetPopularAnimePageMedia) GetBannerImage() string { return v.BannerImage }

// GetCoverImage returns GetPopularAnimePageMedia.CoverImage, and is useful for accessing the field via an interface.
func (v *GetPopularAnimePageMedia) GetCoverImage() GetPopularAnimePageMediaCoverImage {
	return v.CoverImage
}

// GetDescription returns GetPopularAnimePageMedia.Description, and is useful for accessing the field via an interface.
func (v *GetPopularAnimePageMedia) GetDescription() string { return v.Description }

// GetFormat returns GetPopularAnimePageMedia.Format, and is useful for accessing the field via an interface.
func (v *GetPopularAnimePageMedia) GetFormat() MediaFormat { return v.Format }

// GetEpisodes returns GetPopularAnimePageMedia.Episodes, and is useful for accessing the field via an interface.
func (v *GetPopularAnimePageMedia) GetEpisodes() int { return v.Episodes }

// GetStartDate returns GetPopularAnimePageMedia.StartDate, and is useful for accessing the field via an interface.
func (v *GetPopularAnimePageMedia) GetStartDate() GetPopularAnimePageMediaStartDateFuzzyDate {
	return v.StartDate
}

// GetPopularAnimePageMediaCoverImage includes the requested fields of the GraphQL type MediaCoverImage.
type GetPopularAnimePageMediaCoverImage struct {
	// The cover image url of the media at a large size
	Large string `json:"large"`
	// The cover image url of the media at its largest size. If this size isn't available, large will be provided instead.
	ExtraLarge string `json:"extraLarge"`
}

// GetLarge returns GetPopularAnimePageMediaCoverImage.Large, and is useful for accessing the field via an interface.
func (v *GetPopularAnimePageMediaCoverImage) GetLarge() string { return v.Large }

// GetExtraLarge returns GetPopularAnimePageMediaCoverImage.ExtraLarge, and is useful for accessing the field via an interface.
func (v *GetPopularAnimePageMediaCoverImage) GetExtraLarge() string { return v.ExtraLarge }

// GetPopularAnimePageMediaStartDateFuzzyDate includes the requested fields of the GraphQL type FuzzyDate.
// The GraphQL type's documentation follows.
//
// Date object that allows for incomplete date values (fuzzy)
type GetPopularAnimePageMediaStartDateFuzzyDate struct {
	// Numeric Year (2017)
	Year int `json:"year"`
	// Numeric Month (3)
	Month int `json:"month"`
	// Numeric Day (24)
	Day int `json:"day"`
}

// GetYear returns GetPopularAnimePageMediaStartDateFuzzyDate.Year, and is useful for accessing the field via an interface.
func (v *GetPopularAnimePageMediaStartDateFuzzyDate) GetYear() int { return v.Year }

// GetMonth returns GetPopularAnimePageMediaStartDateFuzzyDate.Month, and is useful for accessing the field via an interface.
func (v *GetPopularAnimePageMediaStartDateFuzzyDate) GetMonth() int { return v.Month }

// GetDay returns GetPopularAnimePageMediaStartDateFuzzyDate.Day, and is useful for accessing the field via an interface.
func (v *GetPopularAnimePageMediaStartDateFuzzyDate) GetDay() int { return v.Day }

// GetPopularAnimePageMediaTitle includes the requested fields of the GraphQL type MediaTitle.
// The GraphQL type's documentation follows.
//
// The official titles of the media in various languages
type GetPopularAnimePageMediaTitle struct {
	// The romanization of the native language title
	Romaji string `json:"romaji"`
}

// GetRomaji returns GetPopularAnimePageMediaTitle.Romaji, and is useful for accessing the field via an interface.
func (v *GetPopularAnimePageMediaTitle) GetRomaji() string { return v.Romaji }

// GetPopularAnimeResponse is returned by GetPopularAnime on success.
type GetPopularAnimeResponse struct {
	Page GetPopularAnimePage `json:"page"`
}

// GetPage returns GetPopularAnimeResponse.Page, and is useful for accessing the field via an interface.
func (v *GetPopularAnimeResponse) GetPage() GetPopularAnimePage { return v.Page }

// GetSeasonalAnimePage includes the requested fields of the GraphQL type Page.
// The GraphQL type's documentation follows.
//
// Page of data
type GetSeasonalAnimePage struct {
	Media []GetSeasonalAnimePageMedia `json:"media"`
}

// GetMedia returns GetSeasonalAnimePage.Media, and is useful for accessing the field via an interface.
func (v *GetSeasonalAnimePage) GetMedia() []GetSeasonalAnimePageMedia { return v.Media }

// GetSeasonalAnimePageMedia includes the requested fields of the GraphQL type Media.
// The GraphQL type's documentation follows.
//
// Anime or Manga
type GetSeasonalAnimePageMedia struct {
	// The id of the media
	Id int `json:"id"`
	// The mal id of the media
	IdMal int `json:"idMal"`
	// The official titles of the media in various languages
	Title GetSeasonalAnimePageMediaTitle `json:"title"`
	// The type of the media; anime or manga
	Type MediaType `json:"type"`
	// The banner image of the media
	BannerImage string `json:"bannerImage"`
	// The cover images of the media
	CoverImage GetSeasonalAnimePageMediaCoverImage `json:"coverImage"`
	// Short description of the media's story and characters
	Description string `json:"description"`
	// The format the media was released in
	Format MediaFormat `json:"format"`
	// The amount of episodes the anime has when complete
	Episodes int `json:"episodes"`
	// The first official release date of the media
	StartDate GetSeasonalAnimePageMediaStartDateFuzzyDate `json:"startDate"`
}

// GetId returns GetSeasonalAnimePageMedia.Id, and is useful for accessing the field via an interface.
func (v *GetSeasonalAnimePageMedia) GetId() int { return v.Id }

// GetIdMal returns GetSeasonalAnimePageMedia.IdMal, and is useful for accessing the field via an interface.
func (v *GetSeasonalAnimePageMedia) GetIdMal() int { return v.IdMal }

// GetTitle returns GetSeasonalAnimePageMedia.Title, and is useful for accessing the field via an interface.
func (v *GetSeasonalAnimePageMedia) GetTitle() GetSeasonalAnimePageMediaTitle { return v.Title }

// GetType returns GetSeasonalAnimePageMedia.Type, and is useful for accessing the field via an interface.
func (v *GetSeasonalAnimePageMedia) GetType() MediaType { return v.Type }

// GetBannerImage returns GetSeasonalAnimePageMedia.BannerImage, and is useful for accessing the field via an interface.
func (v *GetSeasonalAnimePageMedia) GetBannerImage() string { return v.BannerImage }

// GetCoverImage returns GetSeasonalAnimePageMedia.CoverImage, and is useful for accessing the field via an interface.
func (v *GetSeasonalAnimePageMedia) GetCoverImage() GetSeasonalAnimePageMediaCoverImage {
	return v.CoverImage
}

// GetDescription returns GetSeasonalAnimePageMedia.Description, and is useful for accessing the field via an interface.
func (v *GetSeasonalAnimePageMedia) GetDescription() string { return v.Description }

// GetFormat returns GetSeasonalAnimePageMedia.Format, and is useful for accessing the field via an interface.
func (v *GetSeasonalAnimePageMedia) GetFormat() MediaFormat { return v.Format }

// GetEpisodes returns GetSeasonalAnimePageMedia.Episodes, and is useful for accessing the field via an interface.
func (v *GetSeasonalAnimePageMedia) GetEpisodes() int { return v.Episodes }

// GetStartDate returns GetSeasonalAnimePageMedia.StartDate, and is useful for accessing the field via an interface.
func (v *GetSeasonalAnimePageMedia) GetStartDate() GetSeasonalAnimePageMediaStartDateFuzzyDate {
	return v.StartDate
}

// GetSeasonalAnimePageMediaCoverImage includes the requested fields of the GraphQL type MediaCoverImage.
type GetSeasonalAnimePageMediaCoverImage struct {
	// The cover image url of the media at a large size
	Large string `json:"large"`
	// The cover image url of the media at its largest size. If this size isn't available, large will be provided instead.
	ExtraLarge string `json:"extraLarge"`
}

// GetLarge returns GetSeasonalAnimePageMediaCoverImage.Large, and is useful for accessing the field via an interface.
func (v *GetSeasonalAnimePageMediaCoverImage) GetLarge() string { return v.Large }

// GetExtraLarge returns GetSeasonalAnimePageMediaCoverImage.ExtraLarge, and is useful for accessing the field via an interface.
func (v *GetSeasonalAnimePageMediaCoverImage) GetExtraLarge() string { return v.ExtraLarge }

// GetSeasonalAnimePageMediaStartDateFuzzyDate includes the requested fields of the GraphQL type FuzzyDate.
// The GraphQL type's documentation follows.
//
// Date object that allows for incomplete date values (fuzzy)
type GetSeasonalAnimePageMediaStartDateFuzzyDate struct {
	// Numeric Year (2017)
	Year int `json:"year"`
	// Numeric Month (3)
	Month int `json:"month"`
	// Numeric Day (24)
	Day int `json:"day"`
}

// GetYear returns GetSeasonalAnimePageMediaStartDateFuzzyDate.Year, and is useful for accessing the field via an interface.
func (v *GetSeasonalAnimePageMediaStartDateFuzzyDate) GetYear() int { return v.Year }

// GetMonth returns GetSeasonalAnimePageMediaStartDateFuzzyDate.Month, and is useful for accessing the field via an interface.
func (v *GetSeasonalAnimePageMediaStartDateFuzzyDate) GetMonth() int { return v.Month }

// GetDay returns GetSeasonalAnimePageMediaStartDateFuzzyDate.Day, and is useful for accessing the field via an interface.
func (v *GetSeasonalAnimePageMediaStartDateFuzzyDate) GetDay() int { return v.Day }

// GetSeasonalAnimePageMediaTitle includes the requested fields of the GraphQL type MediaTitle.
// The GraphQL type's documentation follows.
//
// The official titles of the media in various languages
type GetSeasonalAnimePageMediaTitle struct {
	// The romanization of the native language title
	Romaji string `json:"romaji"`
}

// GetRomaji returns GetSeasonalAnimePageMediaTitle.Romaji, and is useful for accessing the field via an interface.
func (v *GetSeasonalAnimePageMediaTitle) GetRomaji() string { return v.Romaji }

// GetSeasonalAnimeResponse is returned by GetSeasonalAnime on success.
type GetSeasonalAnimeResponse struct {
	Page GetSeasonalAnimePage `json:"page"`
}

// GetPage returns GetSeasonalAnimeResponse.Page, and is useful for accessing the field via an interface.
func (v *GetSeasonalAnimeResponse) GetPage() GetSeasonalAnimePage { return v.Page }

// GetTrendingAnimePage includes the requested fields of the GraphQL type Page.
// The GraphQL type's documentation follows.
//
// Page of data
type GetTrendingAnimePage struct {
	Media []GetTrendingAnimePageMedia `json:"media"`
}

// GetMedia returns GetTrendingAnimePage.Media, and is useful for accessing the field via an interface.
func (v *GetTrendingAnimePage) GetMedia() []GetTrendingAnimePageMedia { return v.Media }

// GetTrendingAnimePageMedia includes the requested fields of the GraphQL type Media.
// The GraphQL type's documentation follows.
//
// Anime or Manga
type GetTrendingAnimePageMedia struct {
	// The id of the media
	Id int `json:"id"`
	// The mal id of the media
	IdMal int `json:"idMal"`
	// The official titles of the media in various languages
	Title GetTrendingAnimePageMediaTitle `json:"title"`
	// The type of the media; anime or manga
	Type MediaType `json:"type"`
	// The banner image of the media
	BannerImage string `json:"bannerImage"`
	// The cover images of the media
	CoverImage GetTrendingAnimePageMediaCoverImage `json:"coverImage"`
	// Short description of the media's story and characters
	Description string `json:"description"`
	// The format the media was released in
	Format MediaFormat `json:"format"`
	// The amount of episodes the anime has when complete
	Episodes int `json:"episodes"`
	// The first official release date of the media
	StartDate GetTrendingAnimePageMediaStartDateFuzzyDate `json:"startDate"`
}

// GetId returns GetTrendingAnimePageMedia.Id, and is useful for accessing the field via an interface.
func (v *GetTrendingAnimePageMedia) GetId() int { return v.Id }

// GetIdMal returns GetTrendingAnimePageMedia.IdMal, and is useful for accessing the field via an interface.
func (v *GetTrendingAnimePageMedia) GetIdMal() int { return v.IdMal }

// GetTitle returns GetTrendingAnimePageMedia.Title, and is useful for accessing the field via an interface.
func (v *GetTrendingAnimePageMedia) GetTitle() GetTrendingAnimePageMediaTitle { return v.Title }

// GetType returns GetTrendingAnimePageMedia.Type, and is useful for accessing the field via an interface.
func (v *GetTrendingAnimePageMedia) GetType() MediaType { return v.Type }

// GetBannerImage returns GetTrendingAnimePageMedia.BannerImage, and is useful for accessing the field via an interface.
func (v *GetTrendingAnimePageMedia) GetBannerImage() string { return v.BannerImage }

// GetCoverImage returns GetTrendingAnimePageMedia.CoverImage, and is useful for accessing the field via an interface.
func (v *GetTrendingAnimePageMedia) GetCoverImage() GetTrendingAnimePageMediaCoverImage {
	return v.CoverImage
}

// GetDescription returns GetTrendingAnimePageMedia.Description, and is useful for accessing the field via an interface.
func (v *GetTrendingAnimePageMedia) GetDescription() string { return v.Description }

// GetFormat returns GetTrendingAnimePageMedia.Format, and is useful for accessing the field via an interface.
func (v *GetTrendingAnimePageMedia) GetFormat() MediaFormat { return v.Format }

// GetEpisodes returns GetTrendingAnimePageMedia.Episodes, and is useful for accessing the field via an interface.
func (v *GetTrendingAnimePageMedia) GetEpisodes() int { return v.Episodes }

// GetStartDate returns GetTrendingAnimePageMedia.StartDate, and is useful for accessing the field via an interface.
func (v *GetTrendingAnimePageMedia) GetStartDate() GetTrendingAnimePageMediaStartDateFuzzyDate {
	return v.StartDate
}

// GetTrendingAnimePageMediaCoverImage includes the requested fields of the GraphQL type MediaCoverImage.
type GetTrendingAnimePageMediaCoverImage struct {
	// The cover image url of the media at a large size
	Large string `json:"large"`
	// The cover image url of the media at its largest size. If this size isn't available, large will be provided instead.
	ExtraLarge string `json:"extraLarge"`
}

// GetLarge returns GetTrendingAnimePageMediaCoverImage.Large, and is useful for accessing the field via an interface.
func (v *GetTrendingAnimePageMediaCoverImage) GetLarge() string { return v.Large }

// GetExtraLarge returns GetTrendingAnimePageMediaCoverImage.ExtraLarge, and is useful for accessing the field via an interface.
func (v *GetTrendingAnimePageMediaCoverImage) GetExtraLarge() string { return v.ExtraLarge }

// GetTrendingAnimePageMediaStartDateFuzzyDate includes the requested fields of the GraphQL type FuzzyDate.
// The GraphQL type's documentation follows.
//
// Date object that allows for incomplete date values (fuzzy)
type GetTrendingAnimePageMediaStartDateFuzzyDate struct {
	// Numeric Year (2017)
	Year int `json:"year"`
	// Numeric Month (3)
	Month int `json:"month"`
	// Numeric Day (24)
	Day int `json:"day"`
}

// GetYear returns GetTrendingAnimePageMediaStartDateFuzzyDate.Year, and is useful for accessing the field via an interface.
func (v *GetTrendingAnimePageMediaStartDateFuzzyDate) GetYear() int { return v.Year }

// GetMonth returns GetTrendingAnimePageMediaStartDateFuzzyDate.Month, and is useful for accessing the field via an interface.
func (v *GetTrendingAnimePageMediaStartDateFuzzyDate) GetMonth() int { return v.Month }

// GetDay returns GetTrendingAnimePageMediaStartDateFuzzyDate.Day, and is useful for accessing the field via an interface.
func (v *GetTrendingAnimePageMediaStartDateFuzzyDate) GetDay() int { return v.Day }

// GetTrendingAnimePageMediaTitle includes the requested fields of the GraphQL type MediaTitle.
// The GraphQL type's documentation follows.
//
// The official titles of the media in various languages
type GetTrendingAnimePageMediaTitle struct {
	// The romanization of the native language title
	Romaji string `json:"romaji"`
}

// GetRomaji returns GetTrendingAnimePageMediaTitle.Romaji, and is useful for accessing the field via an interface.
func (v *GetTrendingAnimePageMediaTitle) GetRomaji() string { return v.Romaji }

// GetTrendingAnimeResponse is returned by GetTrendingAnime on success.
type GetTrendingAnimeResponse struct {
	Page GetTrendingAnimePage `json:"page"`
}

// GetPage returns GetTrendingAnimeResponse.Page, and is useful for accessing the field via an interface.
func (v *GetTrendingAnimeResponse) GetPage() GetTrendingAnimePage { return v.Page }

// GetUserAnimeListPage includes the requested fields of the GraphQL type Page.
// The GraphQL type's documentation follows.
//
// Page of data
type GetUserAnimeListPage struct {
	MediaList []GetUserAnimeListPageMediaList `json:"mediaList"`
}

// GetMediaList returns GetUserAnimeListPage.MediaList, and is useful for accessing the field via an interface.
func (v *GetUserAnimeListPage) GetMediaList() []GetUserAnimeListPageMediaList { return v.MediaList }

// GetUserAnimeListPageMediaList includes the requested fields of the GraphQL type MediaList.
// The GraphQL type's documentation follows.
//
// List of anime or manga
type GetUserAnimeListPageMediaList struct {
	// The id of the list entry
	Id int `json:"id"`
	// The watching/reading status
	Status MediaListStatus `json:"status"`
	// The amount of episodes/chapters consumed by the user
	Progress int `json:"progress"`
	// When the entry data was last updated
	UpdatedAt int                                `json:"updatedAt"`
	Media     GetUserAnimeListPageMediaListMedia `json:"media"`
}

// GetId returns GetUserAnimeListPageMediaList.Id, and is useful for accessing the field via an interface.
func (v *GetUserAnimeListPageMediaList) GetId() int { return v.Id }

// GetStatus returns GetUserAnimeListPageMediaList.Status, and is useful for accessing the field via an interface.
func (v *GetUserAnimeListPageMediaList) GetStatus() MediaListStatus { return v.Status }

// GetProgress returns GetUserAnimeListPageMediaList.Progress, and is useful for accessing the field via an interface.
func (v *GetUserAnimeListPageMediaList) GetProgress() int { return v.Progress }

// GetUpdatedAt returns GetUserAnimeListPageMediaList.UpdatedAt, and is useful for accessing the field via an interface.
func (v *GetUserAnimeListPageMediaList) GetUpdatedAt() int { return v.UpdatedAt }

// GetMedia returns GetUserAnimeListPageMediaList.Media, and is useful for accessing the field via an interface.
func (v *GetUserAnimeListPageMediaList) GetMedia() GetUserAnimeListPageMediaListMedia { return v.Media }

// GetUserAnimeListPageMediaListMedia includes the requested fields of the GraphQL type Media.
// The GraphQL type's documentation follows.
//
// Anime or Manga
type GetUserAnimeListPageMediaListMedia struct {
	// The id of the media
	Id int `json:"id"`
	// The mal id of the media
	IdMal int `json:"idMal"`
}

// GetId returns GetUserAnimeListPageMediaListMedia.Id, and is useful for accessing the field via an interface.
func (v *GetUserAnimeListPageMediaListMedia) GetId() int { return v.Id }

// GetIdMal returns GetUserAnimeListPageMediaListMedia.IdMal, and is useful for accessing the field via an interface.
func (v *GetUserAnimeListPageMediaListMedia) GetIdMal() int { return v.IdMal }

// GetUserAnimeListResponse is returned by GetUserAnimeList on success.
type GetUserAnimeListResponse struct {
	Page GetUserAnimeListPage `json:"Page"`
}

// GetPage returns GetUserAnimeListResponse.Page, and is useful for accessing the field via an interface.
func (v *GetUserAnimeListResponse) GetPage() GetUserAnimeListPage { return v.Page }

// GetUserEntryIdMediaList includes the requested fields of the GraphQL type MediaList.
// The GraphQL type's documentation follows.
//
// List of anime or manga
type GetUserEntryIdMediaList struct {
	// The id of the list entry
	Id int `json:"id"`
}

// GetId returns GetUserEntryIdMediaList.Id, and is useful for accessing the field via an interface.
func (v *GetUserEntryIdMediaList) GetId() int { return v.Id }

// GetUserEntryIdResponse is returned by GetUserEntryId on success.
type GetUserEntryIdResponse struct {
	// Media list query
	MediaList GetUserEntryIdMediaList `json:"MediaList"`
}

// GetMediaList returns GetUserEntryIdResponse.MediaList, and is useful for accessing the field via an interface.
func (v *GetUserEntryIdResponse) GetMediaList() GetUserEntryIdMediaList { return v.MediaList }

// The format the media was released in
type MediaFormat string

const (
	// Anime broadcast on television
	MediaFormatTv MediaFormat = "TV"
	// Anime which are under 15 minutes in length and broadcast on television
	MediaFormatTvShort MediaFormat = "TV_SHORT"
	// Anime movies with a theatrical release
	MediaFormatMovie MediaFormat = "MOVIE"
	// Special episodes that have been included in DVD/Blu-ray releases, picture dramas, pilots, etc
	MediaFormatSpecial MediaFormat = "SPECIAL"
	// (Original Video Animation) Anime that have been released directly on DVD/Blu-ray without originally going through a theatrical release or television broadcast
	MediaFormatOva MediaFormat = "OVA"
	// (Original Net Animation) Anime that have been originally released online or are only available through streaming services.
	MediaFormatOna MediaFormat = "ONA"
	// Short anime released as a music video
	MediaFormatMusic MediaFormat = "MUSIC"
	// Professionally published manga with more than one chapter
	MediaFormatManga MediaFormat = "MANGA"
	// Written books released as a series of light novels
	MediaFormatNovel MediaFormat = "NOVEL"
	// Manga with just one chapter
	MediaFormatOneShot MediaFormat = "ONE_SHOT"
)

var AllMediaFormat = []MediaFormat{
	MediaFormatTv,
	MediaFormatTvShort,
	MediaFormatMovie,
	MediaFormatSpecial,
	MediaFormatOva,
	MediaFormatOna,
	MediaFormatMusic,
	MediaFormatManga,
	MediaFormatNovel,
	MediaFormatOneShot,
}

// Media list watching/reading status enum.
type MediaListStatus string

const (
	// Currently watching/reading
	MediaListStatusCurrent MediaListStatus = "CURRENT"
	// Planning to watch/read
	MediaListStatusPlanning MediaListStatus = "PLANNING"
	// Finished watching/reading
	MediaListStatusCompleted MediaListStatus = "COMPLETED"
	// Stopped watching/reading before completing
	MediaListStatusDropped MediaListStatus = "DROPPED"
	// Paused watching/reading
	MediaListStatusPaused MediaListStatus = "PAUSED"
	// Re-watching/reading
	MediaListStatusRepeating MediaListStatus = "REPEATING"
)

var AllMediaListStatus = []MediaListStatus{
	MediaListStatusCurrent,
	MediaListStatusPlanning,
	MediaListStatusCompleted,
	MediaListStatusDropped,
	MediaListStatusPaused,
	MediaListStatusRepeating,
}

type MediaSeason string

const (
	// Months December to February
	MediaSeasonWinter MediaSeason = "WINTER"
	// Months March to May
	MediaSeasonSpring MediaSeason = "SPRING"
	// Months June to August
	MediaSeasonSummer MediaSeason = "SUMMER"
	// Months September to November
	MediaSeasonFall MediaSeason = "FALL"
)

var AllMediaSeason = []MediaSeason{
	MediaSeasonWinter,
	MediaSeasonSpring,
	MediaSeasonSummer,
	MediaSeasonFall,
}

// Media type enum, anime or manga.
type MediaType string

const (
	// Japanese Anime
	MediaTypeAnime MediaType = "ANIME"
	// Asian comic
	MediaTypeManga MediaType = "MANGA"
)

var AllMediaType = []MediaType{
	MediaTypeAnime,
	MediaTypeManga,
}

// SaveMediaListResponse is returned by SaveMediaList on success.
type SaveMediaListResponse struct {
	// Create or update a media list entry
	SaveMediaListEntry SaveMediaListSaveMediaListEntryMediaList `json:"SaveMediaListEntry"`
}

// GetSaveMediaListEntry returns SaveMediaListResponse.SaveMediaListEntry, and is useful for accessing the field via an interface.
func (v *SaveMediaListResponse) GetSaveMediaListEntry() SaveMediaListSaveMediaListEntryMediaList {
	return v.SaveMediaListEntry
}

// SaveMediaListSaveMediaListEntryMediaList includes the requested fields of the GraphQL type MediaList.
// The GraphQL type's documentation follows.
//
// List of anime or manga
type SaveMediaListSaveMediaListEntryMediaList struct {
	// The id of the list entry
	Id int `json:"id"`
	// The watching/reading status
	Status MediaListStatus `json:"status"`
	// The amount of episodes/chapters consumed by the user
	Progress int `json:"progress"`
	// When the entry data was last updated
	UpdatedAt int                                           `json:"updatedAt"`
	Media     SaveMediaListSaveMediaListEntryMediaListMedia `json:"media"`
}

// GetId returns SaveMediaListSaveMediaListEntryMediaList.Id, and is useful for accessing the field via an interface.
func (v *SaveMediaListSaveMediaListEntryMediaList) GetId() int { return v.Id }

// GetStatus returns SaveMediaListSaveMediaListEntryMediaList.Status, and is useful for accessing the field via an interface.
func (v *SaveMediaListSaveMediaListEntryMediaList) GetStatus() MediaListStatus { return v.Status }

// GetProgress returns SaveMediaListSaveMediaListEntryMediaList.Progress, and is useful for accessing the field via an interface.
func (v *SaveMediaListSaveMediaListEntryMediaList) GetProgress() int { return v.Progress }

// GetUpdatedAt returns SaveMediaListSaveMediaListEntryMediaList.UpdatedAt, and is useful for accessing the field via an interface.
func (v *SaveMediaListSaveMediaListEntryMediaList) GetUpdatedAt() int { return v.UpdatedAt }

// GetMedia returns SaveMediaListSaveMediaListEntryMediaList.Media, and is useful for accessing the field via an interface.
func (v *SaveMediaListSaveMediaListEntryMediaList) GetMedia() SaveMediaListSaveMediaListEntryMediaListMedia {
	return v.Media
}

// SaveMediaListSaveMediaListEntryMediaListMedia includes the requested fields of the GraphQL type Media.
// The GraphQL type's documentation follows.
//
// Anime or Manga
type SaveMediaListSaveMediaListEntryMediaListMedia struct {
	// The id of the media
	Id int `json:"id"`
	// The mal id of the media
	IdMal int `json:"idMal"`
}

// GetId returns SaveMediaListSaveMediaListEntryMediaListMedia.Id, and is useful for accessing the field via an interface.
func (v *SaveMediaListSaveMediaListEntryMediaListMedia) GetId() int { return v.Id }

// GetIdMal returns SaveMediaListSaveMediaListEntryMediaListMedia.IdMal, and is useful for accessing the field via an interface.
func (v *SaveMediaListSaveMediaListEntryMediaListMedia) GetIdMal() int { return v.IdMal }

// __DeleteMediaListEntryInput is used internally by genqlient
type __DeleteMediaListEntryInput struct {
	MediaListEntryId int `json:"mediaListEntryId"`
}

// GetMediaListEntryId returns __DeleteMediaListEntryInput.MediaListEntryId, and is useful for accessing the field via an interface.
func (v *__DeleteMediaListEntryInput) GetMediaListEntryId() int { return v.MediaListEntryId }

// __GetAnimeDetailsInput is used internally by genqlient
type __GetAnimeDetailsInput struct {
	IdMal int `json:"idMal"`
}

// GetIdMal returns __GetAnimeDetailsInput.IdMal, and is useful for accessing the field via an interface.
func (v *__GetAnimeDetailsInput) GetIdMal() int { return v.IdMal }

// __GetAnimeIdInput is used internally by genqlient
type __GetAnimeIdInput struct {
	IdIn    []int `json:"idIn"`
	IdMalIn []int `json:"idMalIn"`
}

// GetIdIn returns __GetAnimeIdInput.IdIn, and is useful for accessing the field via an interface.
func (v *__GetAnimeIdInput) GetIdIn() []int { return v.IdIn }

// GetIdMalIn returns __GetAnimeIdInput.IdMalIn, and is useful for accessing the field via an interface.
func (v *__GetAnimeIdInput) GetIdMalIn() []int { return v.IdMalIn }

// __GetSeasonalAnimeInput is used internally by genqlient
type __GetSeasonalAnimeInput struct {
	Year   int         `json:"year"`
	Season MediaSeason `json:"season"`
}

// GetYear returns __GetSeasonalAnimeInput.Year, and is useful for accessing the field via an interface.
func (v *__GetSeasonalAnimeInput) GetYear() int { return v.Year }

// GetSeason returns __GetSeasonalAnimeInput.Season, and is useful for accessing the field via an interface.
func (v *__GetSeasonalAnimeInput) GetSeason() MediaSeason { return v.Season }

// __GetUserAnimeListInput is used internally by genqlient
type __GetUserAnimeListInput struct {
	Page    int `json:"page"`
	PerPage int `json:"perPage"`
	UserId  int `json:"userId"`
}

// GetPage returns __GetUserAnimeListInput.Page, and is useful for accessing the field via an interface.
func (v *__GetUserAnimeListInput) GetPage() int { return v.Page }

// GetPerPage returns __GetUserAnimeListInput.PerPage, and is useful for accessing the field via an interface.
func (v *__GetUserAnimeListInput) GetPerPage() int { return v.PerPage }

// GetUserId returns __GetUserAnimeListInput.UserId, and is useful for accessing the field via an interface.
func (v *__GetUserAnimeListInput) GetUserId() int { return v.UserId }

// __GetUserEntryIdInput is used internally by genqlient
type __GetUserEntryIdInput struct {
	MediaId int `json:"mediaId"`
	UserId  int `json:"userId"`
}

// GetMediaId returns __GetUserEntryIdInput.MediaId, and is useful for accessing the field via an interface.
func (v *__GetUserEntryIdInput) GetMediaId() int { return v.MediaId }

// GetUserId returns __GetUserEntryIdInput.UserId, and is useful for accessing the field via an interface.
func (v *__GetUserEntryIdInput) GetUserId() int { return v.UserId }

// __SaveMediaListInput is used internally by genqlient
type __SaveMediaListInput struct {
	MediaId  int             `json:"mediaId"`
	Status   MediaListStatus `json:"status"`
	Progress int             `json:"progress"`
}

// GetMediaId returns __SaveMediaListInput.MediaId, and is useful for accessing the field via an interface.
func (v *__SaveMediaListInput) GetMediaId() int { return v.MediaId }

// GetStatus returns __SaveMediaListInput.Status, and is useful for accessing the field via an interface.
func (v *__SaveMediaListInput) GetStatus() MediaListStatus { return v.Status }

// GetProgress returns __SaveMediaListInput.Progress, and is useful for accessing the field via an interface.
func (v *__SaveMediaListInput) GetProgress() int { return v.Progress }

// The mutation executed by DeleteMediaListEntry.
const DeleteMediaListEntry_Operation = `
mutation DeleteMediaListEntry ($mediaListEntryId: Int) {
	DeleteMediaListEntry(id: $mediaListEntryId) {
		deleted
	}
}
`

func DeleteMediaListEntry(
	ctx_ context.Context,
	client_ graphql.Client,
	mediaListEntryId int,
) (data_ *DeleteMediaListEntryResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "DeleteMediaListEntry",
		Query:  DeleteMediaListEntry_Operation,
		Variables: &__DeleteMediaListEntryInput{
			MediaListEntryId: mediaListEntryId,
		},
	}

	data_ = &DeleteMediaListEntryResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetAnimeDetails.
const GetAnimeDetails_Operation = `
query GetAnimeDetails ($idMal: Int!) {
	Media(idMal: $idMal, type: ANIME) {
		id
		idMal
		title {
			romaji
		}
		type
		bannerImage
		coverImage {
			large
			extraLarge
		}
		description
		format
		episodes
		startDate {
			year
			month
			day
		}
	}
}
`

func GetAnimeDetails(
	ctx_ context.Context,
	client_ graphql.Client,
	idMal int,
) (data_ *GetAnimeDetailsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetAnimeDetails",
		Query:  GetAnimeDetails_Operation,
		Variables: &__GetAnimeDetailsInput{
			IdMal: idMal,
		},
	}

	data_ = &GetAnimeDetailsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetAnimeId.
const GetAnimeId_Operation = `
query GetAnimeId ($idIn: [Int], $idMalIn: [Int]) {
	Media(id_in: $idIn, idMal_in: $idMalIn) {
		id
	}
}
`

func GetAnimeId(
	ctx_ context.Context,
	client_ graphql.Client,
	idIn []int,
	idMalIn []int,
) (data_ *GetAnimeIdResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetAnimeId",
		Query:  GetAnimeId_Operation,
		Variables: &__GetAnimeIdInput{
			IdIn:    idIn,
			IdMalIn: idMalIn,
		},
	}

	data_ = &GetAnimeIdResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetPopularAnime.
const GetPopularAnime_Operation = `
query GetPopularAnime {
	page: Page(page: 1, perPage: 10) {
		media(sort: POPULARITY_DESC, type: ANIME, isAdult: false) {
			id
			idMal
			title {
				romaji
			}
			type
			bannerImage
			coverImage {
				large
				extraLarge
			}
			description
			format
			episodes
			startDate {
				year
				month
				day
			}
		}
	}
}
`

func GetPopularAnime(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *GetPopularAnimeResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetPopularAnime",
		Query:  GetPopularAnime_Operation,
	}

	data_ = &GetPopularAnimeResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetSeasonalAnime.
const GetSeasonalAnime_Operation = `
query GetSeasonalAnime ($year: Int!, $season: MediaSeason!) {
	page: Page(page: 1, perPage: 10) {
		media(season: $season, seasonYear: $year, sort: POPULARITY_DESC, type: ANIME, isAdult: false) {
			id
			idMal
			title {
				romaji
			}
			type
			bannerImage
			coverImage {
				large
				extraLarge
			}
			description
			format
			episodes
			startDate {
				year
				month
				day
			}
		}
	}
}
`

func GetSeasonalAnime(
	ctx_ context.Context,
	client_ graphql.Client,
	year int,
	season MediaSeason,
) (data_ *GetSeasonalAnimeResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetSeasonalAnime",
		Query:  GetSeasonalAnime_Operation,
		Variables: &__GetSeasonalAnimeInput{
			Year:   year,
			Season: season,
		},
	}

	data_ = &GetSeasonalAnimeResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetTrendingAnime.
const GetTrendingAnime_Operation = `
query GetTrendingAnime {
	page: Page(page: 1, perPage: 10) {
		media(sort: TRENDING_DESC, type: ANIME, isAdult: false, startDate_greater: 19800101) {
			id
			idMal
			title {
				romaji
			}
			type
			bannerImage
			coverImage {
				large
				extraLarge
			}
			description
			format
			episodes
			startDate {
				year
				month
				day
			}
		}
	}
}
`

func GetTrendingAnime(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *GetTrendingAnimeResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetTrendingAnime",
		Query:  GetTrendingAnime_Operation,
	}

	data_ = &GetTrendingAnimeResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetUserAnimeList.
const GetUserAnimeList_Operation = `
query GetUserAnimeList ($page: Int, $perPage: Int, $userId: Int) {
	Page(page: $page, perPage: $perPage) {
		mediaList(userId: $userId, type: ANIME) {
			id
			status
			progress
			updatedAt
			media {
				id
				idMal
			}
		}
	}
}
`

func GetUserAnimeList(
	ctx_ context.Context,
	client_ graphql.Client,
	page int,
	perPage int,
	userId int,
) (data_ *GetUserAnimeListResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetUserAnimeList",
		Query:  GetUserAnimeList_Operation,
		Variables: &__GetUserAnimeListInput{
			Page:    page,
			PerPage: perPage,
			UserId:  userId,
		},
	}

	data_ = &GetUserAnimeListResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetUserEntryId.
const GetUserEntryId_Operation = `
query GetUserEntryId ($mediaId: Int!, $userId: Int!) {
	MediaList(userId: $userId, mediaId: $mediaId, type: ANIME) {
		id
	}
}
`

func GetUserEntryId(
	ctx_ context.Context,
	client_ graphql.Client,
	mediaId int,
	userId int,
) (data_ *GetUserEntryIdResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetUserEntryId",
		Query:  GetUserEntryId_Operation,
		Variables: &__GetUserEntryIdInput{
			MediaId: mediaId,
			UserId:  userId,
		},
	}

	data_ = &GetUserEntryIdResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by SaveMediaList.
const SaveMediaList_Operation = `
mutation SaveMediaList ($mediaId: Int, $status: MediaListStatus, $progress: Int) {
	SaveMediaListEntry(mediaId: $mediaId, status: $status, progress: $progress) {
		id
		status
		progress
		updatedAt
		media {
			id
			idMal
		}
	}
}
`

func SaveMediaList(
	ctx_ context.Context,
	client_ graphql.Client,
	mediaId int,
	status MediaListStatus,
	progress int,
) (data_ *SaveMediaListResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "SaveMediaList",
		Query:  SaveMediaList_Operation,
		Variables: &__SaveMediaListInput{
			MediaId:  mediaId,
			Status:   status,
			Progress: progress,
		},
	}

	data_ = &SaveMediaListResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
