// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package graphql

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// GetMediaByMalIdMedia includes the requested fields of the GraphQL type Media.
// The GraphQL type's documentation follows.
//
// Anime or Manga
type GetMediaByMalIdMedia struct {
	// The id of the media
	Id int `json:"id"`
	// The official titles of the media in various languages
	Title GetMediaByMalIdMediaTitle `json:"title"`
}

// GetId returns GetMediaByMalIdMedia.Id, and is useful for accessing the field via an interface.
func (v *GetMediaByMalIdMedia) GetId() int { return v.Id }

// GetTitle returns GetMediaByMalIdMedia.Title, and is useful for accessing the field via an interface.
func (v *GetMediaByMalIdMedia) GetTitle() GetMediaByMalIdMediaTitle { return v.Title }

// GetMediaByMalIdMediaTitle includes the requested fields of the GraphQL type MediaTitle.
// The GraphQL type's documentation follows.
//
// The official titles of the media in various languages
type GetMediaByMalIdMediaTitle struct {
	// The romanization of the native language title
	Romaji string `json:"romaji"`
	// The official english title
	English string `json:"english"`
	// Official title in it's native language
	Native string `json:"native"`
}

// GetRomaji returns GetMediaByMalIdMediaTitle.Romaji, and is useful for accessing the field via an interface.
func (v *GetMediaByMalIdMediaTitle) GetRomaji() string { return v.Romaji }

// GetEnglish returns GetMediaByMalIdMediaTitle.English, and is useful for accessing the field via an interface.
func (v *GetMediaByMalIdMediaTitle) GetEnglish() string { return v.English }

// GetNative returns GetMediaByMalIdMediaTitle.Native, and is useful for accessing the field via an interface.
func (v *GetMediaByMalIdMediaTitle) GetNative() string { return v.Native }

// GetMediaByMalIdResponse is returned by GetMediaByMalId on success.
type GetMediaByMalIdResponse struct {
	// Media query
	Media GetMediaByMalIdMedia `json:"Media"`
}

// GetMedia returns GetMediaByMalIdResponse.Media, and is useful for accessing the field via an interface.
func (v *GetMediaByMalIdResponse) GetMedia() GetMediaByMalIdMedia { return v.Media }

// __GetMediaByMalIdInput is used internally by genqlient
type __GetMediaByMalIdInput struct {
	IdMal int `json:"idMal"`
}

// GetIdMal returns __GetMediaByMalIdInput.IdMal, and is useful for accessing the field via an interface.
func (v *__GetMediaByMalIdInput) GetIdMal() int { return v.IdMal }

// The query executed by GetMediaByMalId.
const GetMediaByMalId_Operation = `
query GetMediaByMalId ($idMal: Int!) {
	Media(idMal: $idMal) {
		id
		title {
			romaji
			english
			native
		}
	}
}
`

func GetMediaByMalId(
	ctx_ context.Context,
	client_ graphql.Client,
	idMal int,
) (data_ *GetMediaByMalIdResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetMediaByMalId",
		Query:  GetMediaByMalId_Operation,
		Variables: &__GetMediaByMalIdInput{
			IdMal: idMal,
		},
	}

	data_ = &GetMediaByMalIdResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
