# production build
FROM golang:1.24.5-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /api ./cmd/api

# final runtime image
FROM alpine:3.20
WORKDIR /app

COPY --from=builder /api /app/api
COPY --chmod=755 entrypoint.sh /app/entrypoint.sh

RUN adduser -D aniways
USER aniways

CMD ["/app/entrypoint.sh", "/app/api"]
