services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3
    secrets:
      - postgres_password

  redis:
    image: redis:latest
    command:
      ["redis-server", "--requirepass", "$(cat /run/secrets/redis_password)"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    secrets:
      - redis_password

volumes:
  db_data:
  redis_data:

secrets:
  postgres_password:
    external: true
  redis_password:
    external: true
