CREATE TABLE reset_password_tokens (
  token VARCHAR(21) PRIMARY KEY DEFAULT generate_nanoid (),
  user_id VARCHAR(21) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP + INTERVAL '20 minutes',
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
