// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package repository

import (
	"context"
)

// iteratorForInsertMultipleAnimes implements pgx.CopyFromSource.
type iteratorForInsertMultipleAnimes struct {
	rows                 []InsertMultipleAnimesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertMultipleAnimes) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertMultipleAnimes) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Ename,
		r.rows[0].Jname,
		r.rows[0].ImageUrl,
		r.rows[0].Genre,
		r.rows[0].HiAnimeID,
		r.rows[0].MalID,
		r.rows[0].AnilistID,
		r.rows[0].LastEpisode,
		r.rows[0].Season,
		r.rows[0].SeasonYear,
	}, nil
}

func (r iteratorForInsertMultipleAnimes) Err() error {
	return nil
}

func (q *Queries) InsertMultipleAnimes(ctx context.Context, arg []InsertMultipleAnimesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"animes"}, []string{"ename", "jname", "image_url", "genre", "hi_anime_id", "mal_id", "anilist_id", "last_episode", "season", "season_year"}, &iteratorForInsertMultipleAnimes{rows: arg})
}
