// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: desktop_releases.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDesktopReleasesByVersion = `-- name: DeleteDesktopReleasesByVersion :exec
DELETE FROM desktop_releases
WHERE version = $1
`

func (q *Queries) DeleteDesktopReleasesByVersion(ctx context.Context, version string) error {
	_, err := q.db.Exec(ctx, deleteDesktopReleasesByVersion, version)
	return err
}

const getAllDesktopReleases = `-- name: GetAllDesktopReleases :many
SELECT id, version, platform, download_url, file_name, file_size, release_notes, created_at
FROM desktop_releases
ORDER BY version DESC, platform ASC
`

func (q *Queries) GetAllDesktopReleases(ctx context.Context) ([]DesktopRelease, error) {
	rows, err := q.db.Query(ctx, getAllDesktopReleases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DesktopRelease
	for rows.Next() {
		var i DesktopRelease
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Platform,
			&i.DownloadUrl,
			&i.FileName,
			&i.FileSize,
			&i.ReleaseNotes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDesktopReleaseByVersionAndPlatform = `-- name: GetDesktopReleaseByVersionAndPlatform :one
SELECT id, version, platform, download_url, file_name, file_size, release_notes, created_at
FROM desktop_releases
WHERE version = $1
  AND platform = $2
`

type GetDesktopReleaseByVersionAndPlatformParams struct {
	Version  string
	Platform DesktopPlatform
}

func (q *Queries) GetDesktopReleaseByVersionAndPlatform(ctx context.Context, arg GetDesktopReleaseByVersionAndPlatformParams) (DesktopRelease, error) {
	row := q.db.QueryRow(ctx, getDesktopReleaseByVersionAndPlatform, arg.Version, arg.Platform)
	var i DesktopRelease
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Platform,
		&i.DownloadUrl,
		&i.FileName,
		&i.FileSize,
		&i.ReleaseNotes,
		&i.CreatedAt,
	)
	return i, err
}

const getDesktopReleasesByVersion = `-- name: GetDesktopReleasesByVersion :many
SELECT id, version, platform, download_url, file_name, file_size, release_notes, created_at
FROM desktop_releases
WHERE version = $1
ORDER BY platform ASC
`

func (q *Queries) GetDesktopReleasesByVersion(ctx context.Context, version string) ([]DesktopRelease, error) {
	rows, err := q.db.Query(ctx, getDesktopReleasesByVersion, version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DesktopRelease
	for rows.Next() {
		var i DesktopRelease
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Platform,
			&i.DownloadUrl,
			&i.FileName,
			&i.FileSize,
			&i.ReleaseNotes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestDesktopReleases = `-- name: GetLatestDesktopReleases :many
SELECT id, version, platform, download_url, file_name, file_size, release_notes, created_at
FROM desktop_releases
WHERE version = (
  SELECT version
  FROM desktop_releases
  ORDER BY created_at DESC
  LIMIT 1
)
ORDER BY platform ASC
`

func (q *Queries) GetLatestDesktopReleases(ctx context.Context) ([]DesktopRelease, error) {
	rows, err := q.db.Query(ctx, getLatestDesktopReleases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DesktopRelease
	for rows.Next() {
		var i DesktopRelease
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Platform,
			&i.DownloadUrl,
			&i.FileName,
			&i.FileSize,
			&i.ReleaseNotes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDesktopRelease = `-- name: InsertDesktopRelease :one
INSERT INTO desktop_releases (version, platform, download_url, file_name, file_size, release_notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, version, platform, download_url, file_name, file_size, release_notes, created_at
`

type InsertDesktopReleaseParams struct {
	Version      string
	Platform     DesktopPlatform
	DownloadUrl  string
	FileName     string
	FileSize     int64
	ReleaseNotes pgtype.Text
}

func (q *Queries) InsertDesktopRelease(ctx context.Context, arg InsertDesktopReleaseParams) (DesktopRelease, error) {
	row := q.db.QueryRow(ctx, insertDesktopRelease,
		arg.Version,
		arg.Platform,
		arg.DownloadUrl,
		arg.FileName,
		arg.FileSize,
		arg.ReleaseNotes,
	)
	var i DesktopRelease
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Platform,
		&i.DownloadUrl,
		&i.FileName,
		&i.FileSize,
		&i.ReleaseNotes,
		&i.CreatedAt,
	)
	return i, err
}
