// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: externalsync.sql

package repository

import (
	"context"
)

const deleteLibrarySync = `-- name: DeleteLibrarySync :exec
DELETE FROM external_library_sync
WHERE user_id = $1
  AND anime_id = $2
  AND provider = $3
  AND action = $4
`

type DeleteLibrarySyncParams struct {
	UserID   string
	AnimeID  string
	Provider Provider
	Action   LibraryActions
}

func (q *Queries) DeleteLibrarySync(ctx context.Context, arg DeleteLibrarySyncParams) error {
	_, err := q.db.Exec(ctx, deleteLibrarySync,
		arg.UserID,
		arg.AnimeID,
		arg.Provider,
		arg.Action,
	)
	return err
}

const getAllLibrarySyncsForAnime = `-- name: GetAllLibrarySyncsForAnime :many
SELECT
  user_id, anime_id, provider, action, payload, status, created_at, updated_at
FROM
  external_library_sync
WHERE
  user_id = $1
  AND anime_id = $2
`

type GetAllLibrarySyncsForAnimeParams struct {
	UserID  string
	AnimeID string
}

func (q *Queries) GetAllLibrarySyncsForAnime(ctx context.Context, arg GetAllLibrarySyncsForAnimeParams) ([]ExternalLibrarySync, error) {
	rows, err := q.db.Query(ctx, getAllLibrarySyncsForAnime, arg.UserID, arg.AnimeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExternalLibrarySync
	for rows.Next() {
		var i ExternalLibrarySync
		if err := rows.Scan(
			&i.UserID,
			&i.AnimeID,
			&i.Provider,
			&i.Action,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFailedLibrarySyncs = `-- name: GetFailedLibrarySyncs :many
SELECT
  user_id, anime_id, provider, action, payload, status, created_at, updated_at
FROM
  external_library_sync
WHERE
  user_id = $1
  AND status = 'failed'
`

func (q *Queries) GetFailedLibrarySyncs(ctx context.Context, userID string) ([]ExternalLibrarySync, error) {
	rows, err := q.db.Query(ctx, getFailedLibrarySyncs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExternalLibrarySync
	for rows.Next() {
		var i ExternalLibrarySync
		if err := rows.Scan(
			&i.UserID,
			&i.AnimeID,
			&i.Provider,
			&i.Action,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingLibrarySyncs = `-- name: GetPendingLibrarySyncs :many
SELECT
  user_id, anime_id, provider, action, payload, status, created_at, updated_at
FROM
  external_library_sync
WHERE
  user_id = $1
  AND status = 'pending'
`

func (q *Queries) GetPendingLibrarySyncs(ctx context.Context, userID string) ([]ExternalLibrarySync, error) {
	rows, err := q.db.Query(ctx, getPendingLibrarySyncs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExternalLibrarySync
	for rows.Next() {
		var i ExternalLibrarySync
		if err := rows.Scan(
			&i.UserID,
			&i.AnimeID,
			&i.Provider,
			&i.Action,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingLibrarySyncsForAllUsers = `-- name: GetPendingLibrarySyncsForAllUsers :many
SELECT
  user_id, anime_id, provider, action, payload, status, created_at, updated_at
FROM
  external_library_sync
WHERE
  status = 'pending'
ORDER BY
  updated_at ASC
`

func (q *Queries) GetPendingLibrarySyncsForAllUsers(ctx context.Context) ([]ExternalLibrarySync, error) {
	rows, err := q.db.Query(ctx, getPendingLibrarySyncsForAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExternalLibrarySync
	for rows.Next() {
		var i ExternalLibrarySync
		if err := rows.Scan(
			&i.UserID,
			&i.AnimeID,
			&i.Provider,
			&i.Action,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLibrarySyncStatus = `-- name: UpdateLibrarySyncStatus :exec
UPDATE
  external_library_sync
SET
  status = $1,
  updated_at = NOW()
WHERE
  user_id = $2
  AND anime_id = $3
  AND provider = $4
  AND action = $5
`

type UpdateLibrarySyncStatusParams struct {
	Status   LibrarySyncStatus
	UserID   string
	AnimeID  string
	Provider Provider
	Action   LibraryActions
}

func (q *Queries) UpdateLibrarySyncStatus(ctx context.Context, arg UpdateLibrarySyncStatusParams) error {
	_, err := q.db.Exec(ctx, updateLibrarySyncStatus,
		arg.Status,
		arg.UserID,
		arg.AnimeID,
		arg.Provider,
		arg.Action,
	)
	return err
}

const upsertLibrarySync = `-- name: UpsertLibrarySync :exec
INSERT INTO external_library_sync(user_id, anime_id, provider, action, payload)
  VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, anime_id, provider, action)
  DO UPDATE SET
    payload = $5,
    status = 'pending',
    updated_at = NOW()
`

type UpsertLibrarySyncParams struct {
	UserID   string
	AnimeID  string
	Provider Provider
	Action   LibraryActions
	Payload  []byte
}

func (q *Queries) UpsertLibrarySync(ctx context.Context, arg UpsertLibrarySyncParams) error {
	_, err := q.db.Exec(ctx, upsertLibrarySync,
		arg.UserID,
		arg.AnimeID,
		arg.Provider,
		arg.Action,
		arg.Payload,
	)
	return err
}
