// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: importjob.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLibraryImportJob = `-- name: CreateLibraryImportJob :one
INSERT INTO library_import_jobs(user_id, provider)
  VALUES ($1, $2)
RETURNING
  id
`

type CreateLibraryImportJobParams struct {
	UserID   string
	Provider Provider
}

func (q *Queries) CreateLibraryImportJob(ctx context.Context, arg CreateLibraryImportJobParams) (string, error) {
	row := q.db.QueryRow(ctx, createLibraryImportJob, arg.UserID, arg.Provider)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getLibraryImportJob = `-- name: GetLibraryImportJob :one
SELECT
  id, user_id, provider, status, error_message, created_at, updated_at, completed_at
FROM
  library_import_jobs
WHERE
  id = $1
`

func (q *Queries) GetLibraryImportJob(ctx context.Context, id string) (LibraryImportJob, error) {
	row := q.db.QueryRow(ctx, getLibraryImportJob, id)
	var i LibraryImportJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getLibraryImportJobByUserId = `-- name: GetLibraryImportJobByUserId :many
SELECT
  id, user_id, provider, status, error_message, created_at, updated_at, completed_at
FROM
  library_import_jobs
WHERE
  user_id = $1
ORDER BY
  created_at DESC
`

func (q *Queries) GetLibraryImportJobByUserId(ctx context.Context, userID string) ([]LibraryImportJob, error) {
	rows, err := q.db.Query(ctx, getLibraryImportJobByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LibraryImportJob
	for rows.Next() {
		var i LibraryImportJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLibraryImportJob = `-- name: UpdateLibraryImportJob :exec
UPDATE
  library_import_jobs
SET
  status = $1::library_import_status,
  error_message = $2,
  updated_at = NOW(),
  completed_at = CASE WHEN $1::library_import_status IN ('completed', 'failed') THEN
    NOW()
  ELSE
    NULL
  END
WHERE
  id = $3
`

type UpdateLibraryImportJobParams struct {
	Status       LibraryImportStatus
	ErrorMessage pgtype.Text
	ID           string
}

func (q *Queries) UpdateLibraryImportJob(ctx context.Context, arg UpdateLibraryImportJobParams) error {
	_, err := q.db.Exec(ctx, updateLibraryImportJob, arg.Status, arg.ErrorMessage, arg.ID)
	return err
}
