// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AiringStatus string

const (
	AiringStatusFinishedAiring  AiringStatus = "finished_airing"
	AiringStatusCurrentlyAiring AiringStatus = "currently_airing"
	AiringStatusNotYetAired     AiringStatus = "not_yet_aired"
	AiringStatusUnknown         AiringStatus = "unknown"
)

func (e *AiringStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AiringStatus(s)
	case string:
		*e = AiringStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AiringStatus: %T", src)
	}
	return nil
}

type NullAiringStatus struct {
	AiringStatus AiringStatus
	Valid        bool // Valid is true if AiringStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAiringStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AiringStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AiringStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAiringStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AiringStatus), nil
}

type Provider string

const (
	ProviderMyanimelist Provider = "myanimelist"
	ProviderAnilist     Provider = "anilist"
)

func (e *Provider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Provider(s)
	case string:
		*e = Provider(s)
	default:
		return fmt.Errorf("unsupported scan type for Provider: %T", src)
	}
	return nil
}

type NullProvider struct {
	Provider Provider
	Valid    bool // Valid is true if Provider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProvider) Scan(value interface{}) error {
	if value == nil {
		ns.Provider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Provider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Provider), nil
}

type Rating string

const (
	RatingPg13    Rating = "pg_13"
	RatingR       Rating = "r"
	RatingValue2  Rating = "r+"
	RatingG       Rating = "g"
	RatingPg      Rating = "pg"
	RatingRx      Rating = "rx"
	RatingUnknown Rating = "unknown"
)

func (e *Rating) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Rating(s)
	case string:
		*e = Rating(s)
	default:
		return fmt.Errorf("unsupported scan type for Rating: %T", src)
	}
	return nil
}

type NullRating struct {
	Rating Rating
	Valid  bool // Valid is true if Rating is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRating) Scan(value interface{}) error {
	if value == nil {
		ns.Rating, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Rating.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRating) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Rating), nil
}

type Season string

const (
	SeasonWinter  Season = "winter"
	SeasonSpring  Season = "spring"
	SeasonSummer  Season = "summer"
	SeasonFall    Season = "fall"
	SeasonUnknown Season = "unknown"
)

func (e *Season) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Season(s)
	case string:
		*e = Season(s)
	default:
		return fmt.Errorf("unsupported scan type for Season: %T", src)
	}
	return nil
}

type NullSeason struct {
	Season Season
	Valid  bool // Valid is true if Season is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSeason) Scan(value interface{}) error {
	if value == nil {
		ns.Season, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Season.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSeason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Season), nil
}

type Anime struct {
	ID           string
	Ename        string
	Jname        string
	ImageUrl     string
	Genre        string
	HiAnimeID    string
	MalID        pgtype.Int4
	AnilistID    pgtype.Int4
	LastEpisode  int32
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	SearchVector string
}

type AnimeMetadatum struct {
	MalID              int32
	Description        pgtype.Text
	MainPictureUrl     pgtype.Text
	MediaType          pgtype.Text
	Rating             Rating
	AiringStatus       AiringStatus
	AvgEpisodeDuration pgtype.Int4
	TotalEpisodes      pgtype.Int4
	Studio             pgtype.Text
	Rank               pgtype.Int4
	Mean               pgtype.Float8
	Scoringusers       pgtype.Int4
	Popularity         pgtype.Int4
	AiringStartDate    pgtype.Text
	AiringEndDate      pgtype.Text
	Source             pgtype.Text
	TrailerEmbedUrl    pgtype.Text
	SeasonYear         pgtype.Int4
	Season             Season
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
}

type ResetPasswordToken struct {
	Token     string
	UserID    string
	CreatedAt pgtype.Timestamp
	ExpiresAt pgtype.Timestamp
}

type Session struct {
	ID        string
	UserID    string
	CreatedAt pgtype.Timestamp
	ExpiresAt pgtype.Timestamp
}

type User struct {
	ID             string
	Username       string
	Email          string
	PasswordHash   string
	ProfilePicture pgtype.Text
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type UserToken struct {
	ID           string
	UserID       string
	Token        string
	RefreshToken string
	Provider     Provider
	ExpiresAt    pgtype.Timestamp
	CreatedAt    pgtype.Timestamp
}
