// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AiringStatus string

const (
	AiringStatusFinishedAiring  AiringStatus = "finished_airing"
	AiringStatusCurrentlyAiring AiringStatus = "currently_airing"
	AiringStatusNotYetAired     AiringStatus = "not_yet_aired"
	AiringStatusUnknown         AiringStatus = "unknown"
)

func (e *AiringStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AiringStatus(s)
	case string:
		*e = AiringStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AiringStatus: %T", src)
	}
	return nil
}

type NullAiringStatus struct {
	AiringStatus AiringStatus
	Valid        bool // Valid is true if AiringStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAiringStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AiringStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AiringStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAiringStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AiringStatus), nil
}

type MediaType string

const (
	MediaTypeTv        MediaType = "tv"
	MediaTypeMovie     MediaType = "movie"
	MediaTypeOna       MediaType = "ona"
	MediaTypeOva       MediaType = "ova"
	MediaTypeSpecial   MediaType = "special"
	MediaTypeTvSpecial MediaType = "tv_special"
	MediaTypeMusic     MediaType = "music"
	MediaTypeCm        MediaType = "cm"
	MediaTypePv        MediaType = "pv"
	MediaTypeUnknown   MediaType = "unknown"
)

func (e *MediaType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MediaType(s)
	case string:
		*e = MediaType(s)
	default:
		return fmt.Errorf("unsupported scan type for MediaType: %T", src)
	}
	return nil
}

type NullMediaType struct {
	MediaType MediaType
	Valid     bool // Valid is true if MediaType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMediaType) Scan(value interface{}) error {
	if value == nil {
		ns.MediaType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MediaType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMediaType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MediaType), nil
}

type Rating string

const (
	RatingPg13    Rating = "pg_13"
	RatingR       Rating = "r"
	RatingValue2  Rating = "r+"
	RatingG       Rating = "g"
	RatingPg      Rating = "pg"
	RatingRx      Rating = "rx"
	RatingUnknown Rating = "unknown"
)

func (e *Rating) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Rating(s)
	case string:
		*e = Rating(s)
	default:
		return fmt.Errorf("unsupported scan type for Rating: %T", src)
	}
	return nil
}

type NullRating struct {
	Rating Rating
	Valid  bool // Valid is true if Rating is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRating) Scan(value interface{}) error {
	if value == nil {
		ns.Rating, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Rating.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRating) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Rating), nil
}

type Season string

const (
	SeasonWinter  Season = "winter"
	SeasonSpring  Season = "spring"
	SeasonSummer  Season = "summer"
	SeasonFall    Season = "fall"
	SeasonUnknown Season = "unknown"
)

func (e *Season) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Season(s)
	case string:
		*e = Season(s)
	default:
		return fmt.Errorf("unsupported scan type for Season: %T", src)
	}
	return nil
}

type NullSeason struct {
	Season Season
	Valid  bool // Valid is true if Season is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSeason) Scan(value interface{}) error {
	if value == nil {
		ns.Season, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Season.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSeason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Season), nil
}

type Source string

const (
	SourceOther        Source = "other"
	SourceOriginal     Source = "original"
	SourceManga        Source = "manga"
	Source4KomaManga   Source = "4_koma_manga"
	SourceWebManga     Source = "web_manga"
	SourceDigitalManga Source = "digital_manga"
	SourceNovel        Source = "novel"
	SourceLightNovel   Source = "light_novel"
	SourceVisualNovel  Source = "visual_novel"
	SourceGame         Source = "game"
	SourceCardGame     Source = "card_game"
	SourceBook         Source = "book"
	SourcePictureBook  Source = "picture_book"
	SourceRadio        Source = "radio"
	SourceMusic        Source = "music"
)

func (e *Source) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Source(s)
	case string:
		*e = Source(s)
	default:
		return fmt.Errorf("unsupported scan type for Source: %T", src)
	}
	return nil
}

type NullSource struct {
	Source Source
	Valid  bool // Valid is true if Source is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSource) Scan(value interface{}) error {
	if value == nil {
		ns.Source, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Source.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Source), nil
}

type Anime struct {
	ID           string
	Ename        string
	Jname        string
	ImageUrl     string
	Genre        string
	HiAnimeID    string
	MalID        pgtype.Int4
	AnilistID    pgtype.Int4
	LastEpisode  int32
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	SearchVector string
}

type AnimeMetadatum struct {
	MalID              int32
	Description        pgtype.Text
	MainPictureUrl     pgtype.Text
	MediaType          MediaType
	Rating             Rating
	AiringStatus       AiringStatus
	AvgEpisodeDuration pgtype.Int4
	TotalEpisodes      pgtype.Int4
	Studio             pgtype.Text
	Rank               pgtype.Int4
	Mean               pgtype.Float8
	Scoringusers       pgtype.Int4
	Popularity         pgtype.Int4
	AiringStartDate    pgtype.Text
	AiringEndDate      pgtype.Text
	Source             Source
	TrailerEmbedUrl    pgtype.Text
	SeasonYear         pgtype.Int4
	Season             Season
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
}
