// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: oauth.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOauthToken = `-- name: DeleteOauthToken :exec
DELETE FROM oauth_tokens
WHERE user_id = $1
  AND provider = $2
`

type DeleteOauthTokenParams struct {
	UserID   string
	Provider Provider
}

func (q *Queries) DeleteOauthToken(ctx context.Context, arg DeleteOauthTokenParams) error {
	_, err := q.db.Exec(ctx, deleteOauthToken, arg.UserID, arg.Provider)
	return err
}

const getAllOauthTokensOfUser = `-- name: GetAllOauthTokensOfUser :many
SELECT
  id, user_id, token, refresh_token, provider, expires_at, created_at
FROM
  oauth_tokens
WHERE
  user_id = $1
`

func (q *Queries) GetAllOauthTokensOfUser(ctx context.Context, userID string) ([]OauthToken, error) {
	rows, err := q.db.Query(ctx, getAllOauthTokensOfUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthToken
	for rows.Next() {
		var i OauthToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.RefreshToken,
			&i.Provider,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getToken = `-- name: GetToken :one
SELECT
  id, user_id, token, refresh_token, provider, expires_at, created_at
FROM
  oauth_tokens
WHERE
  user_id = $1
  AND provider = $2
`

type GetTokenParams struct {
	UserID   string
	Provider Provider
}

func (q *Queries) GetToken(ctx context.Context, arg GetTokenParams) (OauthToken, error) {
	row := q.db.QueryRow(ctx, getToken, arg.UserID, arg.Provider)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.RefreshToken,
		&i.Provider,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTokensNearToExpiry = `-- name: GetTokensNearToExpiry :many
SELECT
  id, user_id, token, refresh_token, provider, expires_at, created_at
FROM
  oauth_tokens
WHERE
  expires_at <= NOW() + INTERVAL '10 days'
  AND expires_at > NOW()
`

func (q *Queries) GetTokensNearToExpiry(ctx context.Context) ([]OauthToken, error) {
	rows, err := q.db.Query(ctx, getTokensNearToExpiry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthToken
	for rows.Next() {
		var i OauthToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.RefreshToken,
			&i.Provider,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveOauthToken = `-- name: SaveOauthToken :exec
INSERT INTO oauth_tokens(user_id, token, refresh_token, provider, expires_at)
  VALUES ($1, $2, $3, $4, $5)
`

type SaveOauthTokenParams struct {
	UserID       string
	Token        string
	RefreshToken string
	Provider     Provider
	ExpiresAt    pgtype.Timestamp
}

func (q *Queries) SaveOauthToken(ctx context.Context, arg SaveOauthTokenParams) error {
	_, err := q.db.Exec(ctx, saveOauthToken,
		arg.UserID,
		arg.Token,
		arg.RefreshToken,
		arg.Provider,
		arg.ExpiresAt,
	)
	return err
}

const updateOauthToken = `-- name: UpdateOauthToken :exec
UPDATE
  oauth_tokens
SET
  token = $1,
  refresh_token = $2,
  expires_at = $3
WHERE
  user_id = $4
  AND provider = $5
`

type UpdateOauthTokenParams struct {
	Token        string
	RefreshToken string
	ExpiresAt    pgtype.Timestamp
	UserID       string
	Provider     Provider
}

func (q *Queries) UpdateOauthToken(ctx context.Context, arg UpdateOauthTokenParams) error {
	_, err := q.db.Exec(ctx, updateOauthToken,
		arg.Token,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.UserID,
		arg.Provider,
	)
	return err
}
