// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: passwordreset.sql

package repository

import (
	"context"
)

const createResetPasswordToken = `-- name: CreateResetPasswordToken :one
INSERT INTO reset_password_tokens(user_id)
  VALUES ($1)
RETURNING
  token, user_id, created_at, expires_at
`

func (q *Queries) CreateResetPasswordToken(ctx context.Context, userID string) (ResetPasswordToken, error) {
	row := q.db.QueryRow(ctx, createResetPasswordToken, userID)
	var i ResetPasswordToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteResetPasswordToken = `-- name: DeleteResetPasswordToken :exec
DELETE FROM reset_password_tokens
WHERE token = $1
`

func (q *Queries) DeleteResetPasswordToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteResetPasswordToken, token)
	return err
}

const getResetPasswordToken = `-- name: GetResetPasswordToken :one
SELECT
  token, user_id, created_at, expires_at
FROM
  reset_password_tokens
WHERE
  token = $1
  AND expires_at > NOW()
`

func (q *Queries) GetResetPasswordToken(ctx context.Context, token string) (ResetPasswordToken, error) {
	row := q.db.QueryRow(ctx, getResetPasswordToken, token)
	var i ResetPasswordToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserByResetPasswordToken = `-- name: GetUserByResetPasswordToken :one
SELECT
  users.id, users.username, users.email, users.password_hash, users.profile_picture, users.created_at, users.updated_at
FROM
  reset_password_tokens
  INNER JOIN users ON users.id = reset_password_tokens.user_id
WHERE
  reset_password_tokens.token = $1
  AND reset_password_tokens.expires_at > NOW()
`

func (q *Queries) GetUserByResetPasswordToken(ctx context.Context, token string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByResetPasswordToken, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.ProfilePicture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
