// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package repository

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions(user_id)
  VALUES ($1)
RETURNING
  id, user_id, created_at, expires_at
`

func (q *Queries) CreateSession(ctx context.Context, userID string) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, userID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getUserBySessionID = `-- name: GetUserBySessionID :one
SELECT
  users.id, users.username, users.email, users.password_hash, users.profile_picture, users.created_at, users.updated_at
FROM
  sessions
  INNER JOIN users ON sessions.user_id = users.id
WHERE
  sessions.id = $1
`

func (q *Queries) GetUserBySessionID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySessionID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.ProfilePicture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
