// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: settings.sql

package repository

import (
	"context"
)

const getSettingsOfUser = `-- name: GetSettingsOfUser :one
SELECT
  user_id, auto_next_episode, auto_play_episode, auto_resume_episode, incognito_mode
FROM
  settings
WHERE
  user_id = $1
`

func (q *Queries) GetSettingsOfUser(ctx context.Context, userID string) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettingsOfUser, userID)
	var i Setting
	err := row.Scan(
		&i.UserID,
		&i.AutoNextEpisode,
		&i.AutoPlayEpisode,
		&i.AutoResumeEpisode,
		&i.IncognitoMode,
	)
	return i, err
}

const saveSettings = `-- name: SaveSettings :one
INSERT INTO
  settings (
    user_id,
    auto_next_episode,
    auto_play_episode,
    auto_resume_episode,
    incognito_mode
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5
  )
ON CONFLICT (user_id) DO UPDATE
SET
  auto_next_episode = EXCLUDED.auto_next_episode,
  auto_play_episode = EXCLUDED.auto_play_episode,
  auto_resume_episode = EXCLUDED.auto_resume_episode,
  incognito_mode = EXCLUDED.incognito_mode
RETURNING
  user_id, auto_next_episode, auto_play_episode, auto_resume_episode, incognito_mode
`

type SaveSettingsParams struct {
	UserID            string
	AutoNextEpisode   bool
	AutoPlayEpisode   bool
	AutoResumeEpisode bool
	IncognitoMode     bool
}

func (q *Queries) SaveSettings(ctx context.Context, arg SaveSettingsParams) (Setting, error) {
	row := q.db.QueryRow(ctx, saveSettings,
		arg.UserID,
		arg.AutoNextEpisode,
		arg.AutoPlayEpisode,
		arg.AutoResumeEpisode,
		arg.IncognitoMode,
	)
	var i Setting
	err := row.Scan(
		&i.UserID,
		&i.AutoNextEpisode,
		&i.AutoPlayEpisode,
		&i.AutoResumeEpisode,
		&i.IncognitoMode,
	)
	return i, err
}
